# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(max_length=200)),
                ('msg_content', models.CharField(max_length=200)),
                ('msg_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
